font:
  normal:
    family: JetBrainsMono NF
    style: Regular

  bold:
    family: JetBrainsMono NF
    style: Bold

  italic:
    family: JetBrainsMono NF
    style: Italic

  bold_italic:
    family: JetBrainsMono NF
    style: Bold Italic
  size: 12

# Colors (Molokai Dark)
colors:
  # Default colors
  primary:
    background: '#1B1D1E'
    foreground: '#F8F8F2'
  # Normal colors
  normal:
    black:   '#333333'
    red:     '#C4265E'
    green:   '#86B42B'
    yellow:  '#B3B42B'
    blue:    '#6A7EC8'
    magenta: '#8C6BC8'
    cyan:    '#56ADBC'
    white:   '#E3E3DD'
  # Bright colors
  bright:
    black:   '#666666'
    red:     '#F92672'
    green:   '#A6E22E'
    yellow:  '#E2E22E'
    blue:    '#819AFF'
    magenta: '#AE81FF'
    cyan:    '#66D9EF'
    white:   '#F8F8F2'

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  decorations: full
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
      columns: 120
      lines: 60
